### ISSUE TITLE
Este script Requiere licencia de CPanel?

### ISSUE THREAD

**Issue by jcr2491** [wnpower/cPanel-Config#1]
Puedo instalarlo en un VPS con CentOS 7 sin pagar licencia? lo deseo para utilizar cpanel y configurarlo como hosting para mis correos y Wordpress, pero tengo entendido que se paga por CPanel

**Comment by diyarit** [comment]
the script it self doesn't require a license but it checks if you have a license with CPanel

**Comment by imorandinwnp** [comment]
@jcr2491 : Hola, si es necesario que esté licenciada la IP para poder instalar cPanel
